spring.profiles.active: 'development'

---
spring:
  profiles: 'development'

server:
    port: 9761

eureka:
    instance:
        hostname: valet-discovery-service
        
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://valet-discovery-service:${server.port}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        