spring.profiles.active: 'cloud'

---
spring:
    profiles: 'cloud'
    cloud:
        config:
            discovery:
                enabled: true
            server:
                git:
                    uri: https://github.com/leqcar/sampleConfig

eureka:
    client:
        serviceUrl:
            defaultZone: http://valet-discovery-service:9761/eureka/
server:
    port: 0