server:
    port: 8090

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9761/eureka/
            
spring:
  application:
    name: valet-parking-service            