spring.profiles.active: 'cloud'

---
spring:
  profiles: 'cloud'
  cloud:
    config:
      uri: http://valet-config:8888
server:
    port: 9761

eureka:
    instance:
        hostname: valet-discovery-service
        
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        