spring.profiles.active: 'cloud'

---
spring:
  profiles: 'cloud'

server:
    port: 10010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
zuul:
  routes:
    valet-vehicle-service:
      url: http://localhost:8080
      
ribbon:
  eureka:
    enabled: false
        
logging:
  level:
    ROOT: INFO
    org.springframework.boot.env.PropertySourcesLoader: INFO
    org.springframework.web: DEBUG
    info.tcb: DEBUG
    