spring.profiles.active: 'cloud'

---
spring:
  profiles: 'cloud'
    application:
    name: valet-vehicle-service

server:
    port: 8030

eureka:
    instance:
      leaseRenewalIntervalInSeconds: 10
      statusPageUrlPath: /admin/info
      healthCheckUrlPath: /admin/health
    client:
        serviceUrl:
            defaultZone: http://localhost:9761/eureka/
