spring.profiles.active: 'cloud'

---
spring:
  profiles: 'cloud'
  application:
    name: valet-parking-service   
server:
    port: 8090

eureka:
    client:
        serviceUrl:
            defaultZone: http://valet-discovery-service:9761/eureka/
         